### ISSUE TITLE
Performance of Lineage

### ISSUE THREAD

**Issue by blautob** [ryanfortner/FireHD8-2017#1]
Thanks so much for the guide. I am about to bring back life to my FireHD now.
What lineage OS do you recommend performance-wise?
I want to use the tablet for wawtching videos on the browser attached to my indoor bike especially.

Cheers

**Comment by ryanfortner** [comment]
Hi @blautob!

I'm glad you found this guide useful - I'm currently running the LineageOS 15.1 (Android 8.1) ROM, and I've had no issues so far. In my opinion, this version is the best in terms of balance between stability and app compatibility. 

Your mileage may vary, I am just speaking from experience. Feel free to let me know if you need any assistance.
